### ISSUE TITLE
Conflict between 2 host/remote apps

### ISSUE THREAD

**Issue by alexanderkhivrych** [ruanyl/webpack-remote-types-plugin#14]
I load all remotes from CDN. And usually, start only 1-2 apps locally. Everything works fine. 
However, there is a concern when I have app1, which loads remote modules from app2; app2 also uses remote modules from app1. 

And in this case, it will always throw an error on starting a webpack build that can not load dts zip file because of circle dependency. 

For example, the Shell app loads the profile route from Profile App, and Profile App may use some modules from Shell.

**Comment by alexanderkhivrych** [comment]
One of the solutions is to serve types for local apps using a separate node js server.

**Comment by alexanderkhivrych** [comment]
@ruanyl  So for me developing 2+ apps locally is impossible because each app wants to load modules for each other.

Ok, I can build dts files firstly, then serve them on a separate node js server. However, I should do the same on CI, which is a bit overhead.

**Comment by ruanyl** [comment]
@alexanderkhivrych Would you consider refactoring the code to get rid of the circulating? It sounds like it's not only the build time error but also the circulating may potentially fail the app at runtime, isn't it?

**Comment by alexanderkhivrych** [comment]
@ruanyl No, It is the concept of Module Fedederation too. Container can be host and remote at the same time. 

Example: [Shell]( https://github.com/module-federation/module-federation-examples/blob/master/shared-routing/shell/webpack.config.js) exposes Service Module and consumes all routes from dashboard, profile, etc. [Profile](https://github.com/module-federation/module-federation-examples/blob/master/shared-routing/shell/webpack.config.js) expose Profile route and consume Service from the shell. 

And it is ok and works fine because it works at runtime, but the remote-types-plugin works at build time, so when you load DTS tar zip from CDN - it is fine, but when you develop two apps that reuse modules from each other locally, it will be conflict.

I am thinking of doing a workaround If I need remotes from CDN, I use your plugin. Otherwise, just copy remotes declaration files from another project (It will work with monorepo, but not with polyrepo).

**Comment by alexanderkhivrych** [comment]
@ruanyl Related issue is building two apps on CI. 

For example, you need to make changes in 2 apps, Dashboard and Profile. The dashboard needs a remote module from the profile to render the UserProfile widget on DashboardPage. 
And I could not load remote profile DTS files because it is not in CDN yet, and there is no webpack-dev-server; I built them in parallel on the different nodes.

**Comment by ruanyl** [comment]
@alexanderkhivrych Thanks for the explanation, I think I got the point now. 

For local development, it is possible to have a separate webpack config to only run against the `exposes` and generate the `.d.ts` files with `dts-loader`. And then build the application after that. But it sounds tricky for CI pipelines if they are built on different nodes. 🤔

**Comment by alexanderkhivrych** [comment]
@ruany, I agree that we must use such a plugin only when we load remotes from CDN. In all other cases, use ```dts-loader``` to generate ```.d.ts```  files and then copy them to some shared directory in monorepo to perform the build job. However, in this case, we can only run builds in parallel on the same node, which is fine. In micro-fe, teams may develop 1-2 apps in parallel.

**Comment by alexanderkhivrych** [comment]
@prasannamestha, Hey, any thoughts on this issue from MF's official typescript perspective?

**Comment by alexanderkhivrych** [comment]
@ruanyl I created an example for monorepo on how to keep it simple and have typescript support: 
https://github.com/module-federation/module-federation-examples/tree/master/typescript-monorepo

So I suggest using it for monorepo or looking at the other examples.

And for Polyrepo, use your plugin or @prasannamestha
