### ISSUE TITLE
When I unzip two tgz files,but got only one folder.Is there any options wrong?

### ISSUE THREAD

**Issue by rurounibatousai** [ruanyl/webpack-remote-types-plugin#16]
![image](https://user-images.githubusercontent.com/42639431/196896127-fa49eb24-9cf9-44b5-a737-ed5348d05454.png)
I download two tgz files,but after unzip these got only one folder:
![image](https://user-images.githubusercontent.com/42639431/196896407-8eff0507-7f72-4696-a116-8c30c47d82c7.png)
my expect is get two folder,like:
types
|-jusdaMFSider
|-|-sider.d.ts
|-jusdaMFError
|-|-error.d.ts

**Comment by ruanyl** [comment]
@rurounibatousai can you share your webpack configuration?

**Comment by rurounibatousai** [comment]
> @rurounibatousai can you share your webpack configuration?

Thanks for your reply!
I use this plugin in umi project,and i had wrote a plugin to support this,in this plugin,i use webpack-chain to change my webpack.config.js
Here is my webpack-chain config part:
```javascript
const dtsComponents = ['jusdaMFError', 'jusdaMFSider'];
    for(let item of dtsComponents) {
        config.plugin(item).use(WebpackRemoteTypesPlugin, [
            {
                remotes: {
                    jusdaMF: getTypesConfig.url ? `jusdaMF@${getTypesConfig.url}` : 'jusdaMF@http://localhost:3000/'
                },
                outputDir: getTypesConfig.unpackagePath ? getTypesConfig.unpackagePath : 'types/mf',
                remoteFileName: `${item}-dts.tgz`,
            },
        ]);
    }
```
Hope this can help you!Sorry for my poor English...

**Comment by rurounibatousai** [comment]
> @rurounibatousai can you share your webpack configuration?

I rechecked my tgz files and found the folder is the same name,that cause "tar x" unzip the same name folder,so the .d.ts files be merged in one folder!
That because my package.json command is the same.😂
MY BAD!
I'm sorry!😢
Close this issue😊.Thank you so much!
