### ISSUE TITLE
WebpackRemoteTypesPlugin is not a constructor

### ISSUE THREAD

**Issue by MrChaker** [ruanyl/webpack-remote-types-plugin#17]
I install the package with npm , in webpack config I required it and added code in plugins , it's saying WebpackRemoteTypesPlugin is not a constructor

**Comment by andrewworld** [comment]
@ruanyl  @MrChaker I have the same problem, but changing `exports.default` to `module.export` in `lib/index.js` fixed the issue, so it may be something with compiling config. Have you found another solution?

**Comment by ruanyl** [comment]
@MrChaker @andrewworld Thanks for reporting this, could you try this?
```js
const WebpackRemoteTypesPlugin = require('webpack-remote-types-plugin').default
```

**Comment by MrChaker** [comment]
@andrewworld I recommand to use @ruanyl  solution since you don't have to modify the library's code .
