### ISSUE TITLE
[webpack-dev-middleware] Error: TAR_BAD_ARCHIVE: Unrecognized archive format

### ISSUE THREAD

**Issue by lokesh-shell** [ruanyl/webpack-remote-types-plugin#18]
when i run command npm run start below error output is coming
please find the webpack config at the end

> app2@1.0.0 start
> webpack serve --open --mode development

 [webpack-dev-server] Project is running at:
 [webpack-dev-server] Loopback: http://localhost:3001/
 [webpack-dev-server] On Your Network (IPv4): http://10.190.171.89:3001/
 [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:3001/
 [webpack-dev-server] Content not from webpack is served from '/Users/lokesh.kandala/Documents/typescript/app2/public' directory
 [webpack-dev-server] 404s will fallback to '/index.html'
Downloading:  http://localhost:3000/app-dts.tgz
Saved:  /Users/lokesh.kandala/Documents/typescript/app2/types/app-dts.tgz
[webpack-dev-middleware] Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Unpack.warn (/Users/lokesh.kandala/Documents/typescript/app2/node_modules/tar/lib/warn-mixin.js:21:40)
    at Unpack.warn (/Users/lokesh.kandala/Documents/typescript/app2/node_modules/tar/lib/unpack.js:229:18)
    at Unpack.<anonymous> (/Users/lokesh.kandala/Documents/typescript/app2/node_modules/tar/lib/parse.js:83:14)
    at Unpack.emit (node:events:525:35)
    at [emit] (/Users/lokesh.kandala/Documents/typescript/app2/node_modules/tar/lib/parse.js:303:12)
    at [maybeEnd] (/Users/lokesh.kandala/Documents/typescript/app2/node_modules/tar/lib/parse.js:426:17)
    at [consumeChunk] (/Users/lokesh.kandala/Documents/typescript/app2/node_modules/tar/lib/parse.js:458:21)
    at Unpack.write (/Users/lokesh.kandala/Documents/typescript/app2/node_modules/tar/lib/parse.js:385:25)
    at Unpack.end (/Users/lokesh.kandala/Documents/typescript/app2/node_modules/tar/lib/parse.js:505:14)
    at Pipe.end (/Users/lokesh.kandala/Documents/typescript/app2/node_modules/fs-minipass/node_modules/minipass/index.js:75:17) {
  recoverable: false,
  file: '/Users/lokesh.kandala/Documents/typescript/app2/types/app-dts.tgz',
  cwd: '/Users/lokesh.kandala/Documents/typescript/app2/types',
  code: 'TAR_BAD_ARCHIVE',
  tarCode: 'TAR_BAD_ARCHIVE'
}
 [webpack-dev-middleware] wait until bundle finished: /

**webpack.config.ts**

const HtmlWebPackPlugin = require("html-webpack-plugin");
const ModuleFederationPlugin = require("webpack/lib/container/ModuleFederationPlugin");
const FederatedTypesPlugin = require("@module-federation/typescript").default;
const WebpackRemoteTypesPlugin = require("webpack-remote-types-plugin").default;
const deps = require("./package.json").dependencies;
const federationConfig = {
  name: "app2",
  filename: "remoteEntry.js",
  remotes: {
    app1: "app1@http://localhost:3000/remoteEntry.js",
  },
  exposes: {},
  shared: {
    ...deps,
    react: {
      singleton: true,
      requiredVersion: deps.react,
    },
    "react-dom": {
      singleton: true,
      requiredVersion: deps["react-dom"],
    },
  },
};
module.exports = {
  output: {
    publicPath: "http://localhost:3001/",
  },

  resolve: {
    extensions: [".tsx", ".ts", ".jsx", ".js", ".json"],
  },

  devServer: {
    port: 3001,
    historyApiFallback: true,
  },

  module: {
    rules: [
      {
        test: /\.m?js/,
        type: "javascript/auto",
        resolve: {
          fullySpecified: false,
        },
      },
      {
        test: /\.(css|s[ac]ss)$/i,
        use: ["style-loader", "css-loader", "postcss-loader"],
      },
      {
        test: /\.(ts|tsx|js|jsx)$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
        },
      },
    ],
  },

  plugins: [
    new ModuleFederationPlugin(federationConfig),
    // new FederatedTypesPlugin({ federationConfig }),
    new WebpackRemoteTypesPlugin({
      remotes: {
        app: "app@http://localhost:3000/remoteEntry.js",
      },
      outputDir: "types", // supports [name] as the remote name
      remoteFileName: "[name]-dts.tgz", // default filename is [name]-dts.tgz where [name] is the remote name, for example, `app` with the above setup
    }),

    new HtmlWebPackPlugin({
      template: "./src/index.html",
    }),
  ],
};

**Comment by ruanyl** [comment]
Hi @lokesh-shell, how `app-dts.tgz` was generated? The error message says `Error: TAR_BAD_ARCHIVE: Unrecognized archive format`, I assume the tarball is broken. You may verify this by manually opening the file ` /Users/lokesh.kandala/Documents/typescript/app2/types/app-dts.tgz`

**Comment by StasKhitrich** [comment]
Nope, it's still reproducible. I've just encountered it.
It happens with Node 14/16. I get another error on node 10 (not related to the plugin).

**Comment by ruanyl** [comment]
@StasKhitrich Could you share more context? like how did you generate the `.tgz` file? Is it file valid?

**Comment by lokesh-shell** [comment]
@ruanyl I fixed typescript intellisense issue by including remote files in the tsconfig paths like this  **"shared/Atoms": ["./shared/src/components/atoms"],**

**Comment by rainergp** [comment]
@ruanyl I'm having the exact same issue

<img width="968" alt="image" src="https://user-images.githubusercontent.com/795937/225674410-49f29f5c-0fb8-4a19-9a59-a86dc8622653.png">

My guess is that it is related to this:

<img width="1117" alt="image" src="https://user-images.githubusercontent.com/795937/225673148-a728c02d-fb5d-4d8b-b2ba-3f69a3534776.png">

It looks like Webpack is splitting the file into three chunks, and the plugin is just loading the first one without merging them, so is thinking the file is corrupt. Are you guys taking this into consideration or I'm wrong on this?
