### ISSUE TITLE
alternative use

### ISSUE THREAD

**Issue by JulianWielga** [ruanyl/webpack-remote-types-plugin#6]
fyi, your plugin is a great source side companion for[ filemanager-webpack-plugin](https://github.com/gregnb/filemanager-webpack-plugin#readme) that allows you to create an archive. I prefer that with [federated-types](https://github.com/pixability/federated-types) over yours `dst-loader`

**Comment by ruanyl** [comment]
Thanks for the info, I didn't know `federated-types` before
