### ISSUE TITLE
Support remote types served by https

### ISSUE THREAD

**Issue by denis-heka** [ruanyl/webpack-remote-types-plugin#7]
Hey, love the concept of this plugin.
I'm currently serving my dts.tgz TAR from an https enforced CDN.
I get the following error: 
```
(node:13580) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:155:11)
    at request (http.js:50:10)
    at Object.get (http.js:54:15)
    at node_modules\webpack-remote-types-plugin\lib\index.js:15:24
    at new Promise (<anonymous>)
    at downloadFile (node_modules\webpack-remote-types-plugin\lib\index.js:13:12)
    at downloadFederationTypes (node_modules\webpack-remote-types-plugin\lib\index.js:40:29)
```
It looks like the "http" library doesn't support HTTPS.
https://github.com/ruanyl/webpack-remote-types-plugin/blob/592f3eb73f72b6df3a2baa36c6dfb9a77ea23a99/src/index.ts#L13

- Do you think it would be possible to switch between the "https" and "http" libraries based on the url endpoint?

I'm happy/would like to put a PR in for it, if you think the idea is good

**Comment by ruanyl** [comment]
@denis-heka sounds good to me, PR is welcome :)

**Comment by denis-heka** [comment]
> @denis-heka sounds good to me, PR is welcome :)

```
PS open-source\webpack-remote-types-plugin> git push origin support-https
ERROR: Permission to ruanyl/webpack-remote-types-plugin.git denied to DenisKent.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Got a working branch but unable to push to github to make a PR. Do I need some permissions? Thanks

**Comment by ruanyl** [comment]
@denis-heka You need fork this repo first and then make a PR

**Comment by DenisKent** [comment]
> @denis-heka You need fork this repo first and then make a PR

🤦
